'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace TaxID
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="tinpin", [Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(TaxID.ArrayOfAnyType)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(TaxID.ArrayOfString))>  _
    Partial Public Class tinpin
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private vMessageErrField As TaxID.ArrayOfAnyType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private vIDField As TaxID.ArrayOfAnyType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private vDigitOkField As TaxID.ArrayOfAnyType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private vIsExistField As TaxID.ArrayOfAnyType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property vMessageErr() As TaxID.ArrayOfAnyType
            Get
                Return Me.vMessageErrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.vMessageErrField, value) <> true) Then
                    Me.vMessageErrField = value
                    Me.RaisePropertyChanged("vMessageErr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property vID() As TaxID.ArrayOfAnyType
            Get
                Return Me.vIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.vIDField, value) <> true) Then
                    Me.vIDField = value
                    Me.RaisePropertyChanged("vID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property vDigitOk() As TaxID.ArrayOfAnyType
            Get
                Return Me.vDigitOkField
            End Get
            Set
                If (Object.ReferenceEquals(Me.vDigitOkField, value) <> true) Then
                    Me.vDigitOkField = value
                    Me.RaisePropertyChanged("vDigitOk")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property vIsExist() As TaxID.ArrayOfAnyType
            Get
                Return Me.vIsExistField
            End Get
            Set
                If (Object.ReferenceEquals(Me.vIsExistField, value) <> true) Then
                    Me.vIsExistField = value
                    Me.RaisePropertyChanged("vIsExist")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfAnyType", [Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice", ItemName:="anyType"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfAnyType
        Inherits System.Collections.Generic.List(Of Object)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice", ConfigurationName:="TaxID.checktinpinserviceSoap")>  _
    Public Interface checktinpinserviceSoap
        
        'CODEGEN: Generating message contract since element name username from namespace https://rdws.rd.go.th/serviceRD3/checktinpinservice is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://rdws.rd.go.th/serviceRD3/checktinpinservice/ServiceTIN", ReplyAction:="*")>  _
        Function ServiceTIN(ByVal request As TaxID.ServiceTINRequest) As TaxID.ServiceTINResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://rdws.rd.go.th/serviceRD3/checktinpinservice/ServiceTIN", ReplyAction:="*")>  _
        Function ServiceTINAsync(ByVal request As TaxID.ServiceTINRequest) As System.Threading.Tasks.Task(Of TaxID.ServiceTINResponse)
        
        'CODEGEN: Generating message contract since element name username from namespace https://rdws.rd.go.th/serviceRD3/checktinpinservice is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://rdws.rd.go.th/serviceRD3/checktinpinservice/ServiceTINArr", ReplyAction:="*")>  _
        Function ServiceTINArr(ByVal request As TaxID.ServiceTINArrRequest) As TaxID.ServiceTINArrResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://rdws.rd.go.th/serviceRD3/checktinpinservice/ServiceTINArr", ReplyAction:="*")>  _
        Function ServiceTINArrAsync(ByVal request As TaxID.ServiceTINArrRequest) As System.Threading.Tasks.Task(Of TaxID.ServiceTINArrResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ServiceTINRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ServiceTIN", [Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice", Order:=0)>  _
        Public Body As TaxID.ServiceTINRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TaxID.ServiceTINRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice")>  _
    Partial Public Class ServiceTINRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public TIN As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal username As String, ByVal password As String, ByVal TIN As String)
            MyBase.New
            Me.username = username
            Me.password = password
            Me.TIN = TIN
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ServiceTINResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ServiceTINResponse", [Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice", Order:=0)>  _
        Public Body As TaxID.ServiceTINResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TaxID.ServiceTINResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice")>  _
    Partial Public Class ServiceTINResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ServiceTINResult As TaxID.tinpin
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ServiceTINResult As TaxID.tinpin)
            MyBase.New
            Me.ServiceTINResult = ServiceTINResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ServiceTINArrRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ServiceTINArr", [Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice", Order:=0)>  _
        Public Body As TaxID.ServiceTINArrRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TaxID.ServiceTINArrRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice")>  _
    Partial Public Class ServiceTINArrRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public TINs As TaxID.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal username As String, ByVal password As String, ByVal TINs As TaxID.ArrayOfString)
            MyBase.New
            Me.username = username
            Me.password = password
            Me.TINs = TINs
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ServiceTINArrResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ServiceTINArrResponse", [Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice", Order:=0)>  _
        Public Body As TaxID.ServiceTINArrResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TaxID.ServiceTINArrResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://rdws.rd.go.th/serviceRD3/checktinpinservice")>  _
    Partial Public Class ServiceTINArrResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ServiceTINArrResult As TaxID.tinpin
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ServiceTINArrResult As TaxID.tinpin)
            MyBase.New
            Me.ServiceTINArrResult = ServiceTINArrResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface checktinpinserviceSoapChannel
        Inherits TaxID.checktinpinserviceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class checktinpinserviceSoapClient
        Inherits System.ServiceModel.ClientBase(Of TaxID.checktinpinserviceSoap)
        Implements TaxID.checktinpinserviceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TaxID_checktinpinserviceSoap_ServiceTIN(ByVal request As TaxID.ServiceTINRequest) As TaxID.ServiceTINResponse Implements TaxID.checktinpinserviceSoap.ServiceTIN
            Return MyBase.Channel.ServiceTIN(request)
        End Function
        
        Public Function ServiceTIN(ByVal username As String, ByVal password As String, ByVal TIN As String) As TaxID.tinpin
            Dim inValue As TaxID.ServiceTINRequest = New TaxID.ServiceTINRequest()
            inValue.Body = New TaxID.ServiceTINRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.TIN = TIN
            Dim retVal As TaxID.ServiceTINResponse = CType(Me,TaxID.checktinpinserviceSoap).ServiceTIN(inValue)
            Return retVal.Body.ServiceTINResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TaxID_checktinpinserviceSoap_ServiceTINAsync(ByVal request As TaxID.ServiceTINRequest) As System.Threading.Tasks.Task(Of TaxID.ServiceTINResponse) Implements TaxID.checktinpinserviceSoap.ServiceTINAsync
            Return MyBase.Channel.ServiceTINAsync(request)
        End Function
        
        Public Function ServiceTINAsync(ByVal username As String, ByVal password As String, ByVal TIN As String) As System.Threading.Tasks.Task(Of TaxID.ServiceTINResponse)
            Dim inValue As TaxID.ServiceTINRequest = New TaxID.ServiceTINRequest()
            inValue.Body = New TaxID.ServiceTINRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.TIN = TIN
            Return CType(Me,TaxID.checktinpinserviceSoap).ServiceTINAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TaxID_checktinpinserviceSoap_ServiceTINArr(ByVal request As TaxID.ServiceTINArrRequest) As TaxID.ServiceTINArrResponse Implements TaxID.checktinpinserviceSoap.ServiceTINArr
            Return MyBase.Channel.ServiceTINArr(request)
        End Function
        
        Public Function ServiceTINArr(ByVal username As String, ByVal password As String, ByVal TINs As TaxID.ArrayOfString) As TaxID.tinpin
            Dim inValue As TaxID.ServiceTINArrRequest = New TaxID.ServiceTINArrRequest()
            inValue.Body = New TaxID.ServiceTINArrRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.TINs = TINs
            Dim retVal As TaxID.ServiceTINArrResponse = CType(Me,TaxID.checktinpinserviceSoap).ServiceTINArr(inValue)
            Return retVal.Body.ServiceTINArrResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TaxID_checktinpinserviceSoap_ServiceTINArrAsync(ByVal request As TaxID.ServiceTINArrRequest) As System.Threading.Tasks.Task(Of TaxID.ServiceTINArrResponse) Implements TaxID.checktinpinserviceSoap.ServiceTINArrAsync
            Return MyBase.Channel.ServiceTINArrAsync(request)
        End Function
        
        Public Function ServiceTINArrAsync(ByVal username As String, ByVal password As String, ByVal TINs As TaxID.ArrayOfString) As System.Threading.Tasks.Task(Of TaxID.ServiceTINArrResponse)
            Dim inValue As TaxID.ServiceTINArrRequest = New TaxID.ServiceTINArrRequest()
            inValue.Body = New TaxID.ServiceTINArrRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.TINs = TINs
            Return CType(Me,TaxID.checktinpinserviceSoap).ServiceTINArrAsync(inValue)
        End Function
    End Class
End Namespace
